{% set name = "sixs_json" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/raphidoc/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2d8511ed1898f4a62430df542e94d8fb4d9913ddbb2b535bcac3d649fb677ceb

build:
  number: 1

requirements:
  build:
    - cmake
    - make
    - {{ stdlib("c") }}  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ stdlib("m2w64_c") }}  # [win]
    - {{ compiler("m2w64_c") }}  # [win]
    - {{ compiler("m2w64_fortran") }}  # [win]
    - m2-base  # [win]
  run:
    - m2w64-gcc-libgfortran  # [win]

test:
  files:
    - test_params.txt

about:
  home: https://github.com/raphidoc/sixs_json
  license: MIT
  license_file: LICENSE
  summary: 'The 6S atmospheric radiative transfer model modified with JSON output'

extra:
  recipe-maintainers:
    - raphidoc
